<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_loginlogo</name>
   <tag></tag>
   <elementGuidId>1b4fc443-e821-40c9-8cb2-f05a13154a61</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Fieldwire/img_loginlogo.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Fieldwire/img_loginlogo.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='auth-sign-in']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.login-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>409a9a47-b1e2-4151-959b-6adb3c1626e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-logo</value>
      <webElementGuid>e6e55a73-641d-4fef-9513-a561b731b0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg</value>
      <webElementGuid>6b0d1e74-1fd5-4e3d-89be-c3fde2a76ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg</value>
      <webElementGuid>68c10dcc-dac6-45e2-8f5f-beea468d145b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-sign-in&quot;)/div[@class=&quot;auth-card&quot;]/img[@class=&quot;login-logo&quot;]</value>
      <webElementGuid>5cd6894c-a1b2-4104-b22f-8c7c19da9755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auth-sign-in']/div/img</value>
      <webElementGuid>cbcb375f-ddac-4527-bd6b-f005e83acd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>14f8f94e-e495-4e50-b38e-ad18301aa21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg']</value>
      <webElementGuid>670d4d19-914f-4f58-8fa0-3eca1b0e1f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
