<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mailTextField</name>
   <tag></tag>
   <elementGuidId>21e7ab24-56ed-4f73-9b69-370a0d18491d</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Fieldwire/input_mailTextField.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Fieldwire/input_mailTextField.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3ba799a-b490-42e5-975f-7ca854807109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-invalid ng-dirty ng-valid-parse ng-touched ng-empty ng-valid-email ng-invalid-required</value>
      <webElementGuid>1ee47d74-9622-45dd-8226-bec9d411a799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-input</value>
      <webElementGuid>c2f3f4e2-e010-4296-b7d2-30964581bbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.email</value>
      <webElementGuid>b6115b2f-1cde-4082-9ebb-86729beca7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7a3025bd-18a4-401e-9114-773c41802128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>583b4cfa-fedb-4c60-9a5c-26d71a7856e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>55806495-9053-4dd6-ab59-f3360bb6b875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-input&quot;)</value>
      <webElementGuid>2820ec04-9269-427e-a087-37cd627e6d37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-input']</value>
      <webElementGuid>a21a0dc9-7794-4af3-adcb-ba725106d618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auth-sign-in']/div/form/fieldset/input</value>
      <webElementGuid>978f4b5b-1721-4ffd-a14c-eb3dd223adf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>be1032ea-ee4e-4b9d-a4a9-c8f69afde7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email-input' and @type = 'email' and @placeholder = 'Email address']</value>
      <webElementGuid>e5275874-caa3-4c57-82f4-ed5ebe1159b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
