<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_accountLocked</name>
   <tag></tag>
   <elementGuidId>92e687ef-3602-4818-9153-a85604eb9c7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='links']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>306ab7bb-56d4-4a5d-839e-867e2c022fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>auth.locked_password({ squelch: true })</value>
      <webElementGuid>09224740-e5aa-43a7-b3f5-7c77e38e6e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>{ reload: true }</value>
      <webElementGuid>5940d2b0-3db4-4291-ab3b-14315f96976c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>16cd4dd3-da4e-4fb0-a25e-30c86573ac89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>ACCOUNT_LOCKED</value>
      <webElementGuid>59de1575-21c9-4bd9-b1de-02cfce95fdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>7da026df-6c31-47e2-860b-0cd15b53f6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#!/auth/locked_password?alertDanger=false&amp;squelch=true</value>
      <webElementGuid>7287fee7-83f4-4190-95f9-f6b21850d2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account locked?</value>
      <webElementGuid>30e7f377-8792-44c3-8ddc-096801c3e47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;links&quot;)/div[@class=&quot;view-change&quot;]/a[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>4d0c73fe-a360-480f-971c-42c622cfee1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='links']/div/a</value>
      <webElementGuid>35f61aa3-c374-4128-a7de-f200479dccf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Account locked?')]</value>
      <webElementGuid>06480923-7b80-4f07-8b97-b42193e8f89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[1]</value>
      <webElementGuid>32964af0-55f1-49d8-95aa-cf0784a08abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account'])[1]/preceding::a[1]</value>
      <webElementGuid>4b9b1d27-6b35-4794-a986-f090484087b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboard Shortcuts:'])[1]/preceding::a[2]</value>
      <webElementGuid>5feeb78d-14e4-4ec5-971d-e1364452417e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account locked?']/parent::*</value>
      <webElementGuid>7d8ea2f9-a57b-4ec1-97fd-fe95ab670ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#!/auth/locked_password?alertDanger=false&amp;squelch=true')]</value>
      <webElementGuid>c1e88c57-9aff-4b4a-ba6b-67904cf455d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ceb41fab-5a38-43f9-bff0-9e030e3af2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#!/auth/locked_password?alertDanger=false&amp;squelch=true' and (text() = 'Account locked?' or . = 'Account locked?')]</value>
      <webElementGuid>3c025f91-5032-4d17-8f17-6c2e5423c6e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
