<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_createAccount</name>
   <tag></tag>
   <elementGuidId>884c08d2-e493-4b86-8118-c35ea47d99ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signup-link']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signup-link > a.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>66cadc04-9470-4d4f-a528-5976625255c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>auth.register</value>
      <webElementGuid>514dcd0b-c101-4e71-a0d3-ba9819e2b58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>{ reload: true }</value>
      <webElementGuid>195fbeb2-fe61-4875-8c54-7f365c657a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c564445b-9764-4280-a6f5-413a3f8e4871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>CREATE_ACCOUNT</value>
      <webElementGuid>1ce9a4ba-a9ef-492f-8264-8cdb2a779ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>76a75e0f-00d2-4316-94cf-34173082ca4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#!/auth/register?alertDanger=false</value>
      <webElementGuid>1f79f4c8-0764-41d8-bb34-07da2fa66e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create an account</value>
      <webElementGuid>d75ac5d3-b05f-4216-8951-a45a93721ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup-link&quot;)/a[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>be27aceb-3bc5-4cb8-ba69-c4f08ddb77a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signup-link']/a</value>
      <webElementGuid>b763aa68-81e2-486b-a1a6-a07877efaccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create an account')]</value>
      <webElementGuid>0dfa283b-3dde-4caa-88d7-ddedb24897ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account locked?'])[1]/following::a[1]</value>
      <webElementGuid>6933718b-3b20-4cdc-b4d9-5699368127f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[2]</value>
      <webElementGuid>cbe9def9-522a-4e8a-b642-433072cfc98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboard Shortcuts:'])[1]/preceding::a[1]</value>
      <webElementGuid>81d26994-1ada-436e-a3c5-14054290da06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/preceding::a[1]</value>
      <webElementGuid>4f23f48f-4a3c-490e-9fd7-168c834361a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create an account']/parent::*</value>
      <webElementGuid>39a97082-27e8-4ff2-ad0f-966cb6a2b0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#!/auth/register?alertDanger=false')]</value>
      <webElementGuid>a747fb64-5ee1-4b21-9ef4-cf283c2bb5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>32f9b999-cab5-452d-a2a6-ea9e7b92809c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#!/auth/register?alertDanger=false' and (text() = 'Create an account' or . = 'Create an account')]</value>
      <webElementGuid>ac10ae1f-6943-4721-867b-dc120c902f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
