<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_signUpLogo</name>
   <tag></tag>
   <elementGuidId>2a8a32e0-d0a8-4a43-afdd-057783e8cfa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.login-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fa6b9900-5a06-49f3-b99c-007d560e68f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-logo</value>
      <webElementGuid>52b882dc-5f4c-4ed3-87c1-9dcd73791cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg</value>
      <webElementGuid>2dfdee33-dbdb-48c0-98a0-446d966b166f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg</value>
      <webElementGuid>783f11fd-c158-424e-b2b6-f28eb093453b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/img[@class=&quot;login-logo&quot;]</value>
      <webElementGuid>f312df19-b394-44db-9290-93208f1520c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/img</value>
      <webElementGuid>652a8d20-9f02-4cab-8c95-f691dabeece2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bfacff93-9e21-4750-a50c-6377004e9fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg']</value>
      <webElementGuid>edffbc38-27b4-4378-abdd-76febc94b13f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
