<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_acknowledgementCheckBox</name>
   <tag></tag>
   <elementGuidId>0d54421d-c220-4146-b0e2-b24a6991453f</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Fieldwire Sign Up/input_achknowledgmentCheckBox.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Fieldwire Sign Up/input_achknowledgmentCheckBox.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='explicitAgreement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#explicitAgreement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7be7e263-ad70-4e28-9f3c-c7be1e1fd7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>explicitAgreement</value>
      <webElementGuid>96d71e11-4441-4856-ad8b-c5f6745c733d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>af6068cc-997a-4abe-8d9c-60fefa784c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>explicitAgreementInput.checked</value>
      <webElementGuid>5e541f66-5201-4ab4-834b-0f762c66234e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>520aa9b8-7da8-4671-9070-c0ca37307559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>explicit-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>91c80ace-fa5c-4b6f-a4d8-e15454cebd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>0b73c504-6019-489f-a65d-ed07c4703ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;explicitAgreement&quot;)</value>
      <webElementGuid>781614ff-b3ca-4387-ad89-48a70477508c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='explicitAgreement']</value>
      <webElementGuid>2ae2fd58-1a1b-4748-a4ba-513bce93666e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/div/div/input</value>
      <webElementGuid>3379a5ad-8104-41c5-90e1-fc57bbd0333e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9374b868-998b-417d-8355-b9e3d797a331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'explicitAgreement' and @type = 'checkbox']</value>
      <webElementGuid>06e57965-eb77-4f5c-8ad7-740875bfc9ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
