<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_acknowledgement</name>
   <tag></tag>
   <elementGuidId>2a51e90c-65a3-4fec-9a3e-6e9b61e15e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login']/form/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ea61be3d-c367-46c7-86fe-d348455b59c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>explicitAgreement</value>
      <webElementGuid>8763e323-2335-4133-80cb-ec571d874f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>EXPLICIT_AGREE_TO_TERMS</value>
      <webElementGuid>defc446f-cdb0-4deb-94fe-bed636b63858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate-values</name>
      <type>Main</type>
      <value>termsURLs</value>
      <webElementGuid>5b1e8aeb-0482-46e8-ad7d-7c7c97860518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>62b7e43b-34e8-4542-b4da-6588cd7bd755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I accept the Subscription Agreement and the Service Description on behalf of the represented company.</value>
      <webElementGuid>52b9bca6-59b9-499c-9641-5f1a4907db81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/form[@class=&quot;form-signin ng-invalid ng-invalid-required ng-valid-minlength ng-valid-email ng-valid-pattern ng-dirty ng-valid-parse&quot;]/div[@class=&quot;explicit-terms&quot;]/div[@class=&quot;checkbox&quot;]/label[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>93b9024a-4eb1-4006-b97d-9b46fe40585e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/div/div/label</value>
      <webElementGuid>4e24a103-b046-47a9-9e6f-bb40f6262608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I accept the']/parent::*</value>
      <webElementGuid>0941c6a9-85e1-4994-a6ae-524cf0799a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>7d8f0bb0-69d7-4078-a44d-60694780b796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'I accept the Subscription Agreement and the Service Description on behalf of the represented company.' or . = 'I accept the Subscription Agreement and the Service Description on behalf of the represented company.')]</value>
      <webElementGuid>d96502e6-e68a-4f32-88fb-f8d008abf974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
