<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_privacyPolicy</name>
   <tag></tag>
   <elementGuidId>3dd109d3-f70c-4215-ad5d-80e8c1a35032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='session']/div[2]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.privacy-notice-text.ng-scope > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49c352a3-299e-4cfb-88ea-ea2891ae49b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.fieldwire.com/legal/en/privacy_notice.pdf</value>
      <webElementGuid>4fc9a8b0-a177-4980-8459-45be9c0cddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>44540435-6dc8-42bd-9412-cf45b548236c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy Notice</value>
      <webElementGuid>2a84d80e-579c-48d1-be4e-cd171e0c765c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;session&quot;)/div[@class=&quot;center ng-scope&quot;]/p[@class=&quot;privacy-notice-text ng-scope&quot;]/a[1]</value>
      <webElementGuid>214e876c-92be-44e1-9898-87f5080e7c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='session']/div[2]/p/a</value>
      <webElementGuid>c84c07ac-fc13-4e3b-a75f-1af6818c76d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Privacy Notice')]</value>
      <webElementGuid>b3d8f30b-6b79-4551-9bf0-b120c8a1e900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::a[1]</value>
      <webElementGuid>9c174e07-9634-4c82-bc7c-12d4e1ffc5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create account'])[1]/following::a[2]</value>
      <webElementGuid>595f4198-5e09-4c64-b371-e2b75bc6ea25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboard Shortcuts:'])[1]/preceding::a[1]</value>
      <webElementGuid>5fff5977-c2bd-4d30-9258-35bb5cc7e07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/preceding::a[1]</value>
      <webElementGuid>86d9ba66-98f3-4f35-9e85-c451c305d900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privacy Notice']/parent::*</value>
      <webElementGuid>ba23bd3f-f2cd-41ff-819b-b050d04f477b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.fieldwire.com/legal/en/privacy_notice.pdf')]</value>
      <webElementGuid>36146da9-bcb6-4b7f-86f7-9991dbe664ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>c8115e6b-5544-4015-a379-47969892e58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.fieldwire.com/legal/en/privacy_notice.pdf' and (text() = 'Privacy Notice' or . = 'Privacy Notice')]</value>
      <webElementGuid>fc5166c0-1682-424b-89d6-2eb2287bae99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
