<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_submitTask</name>
   <tag></tag>
   <elementGuidId>4b759e63-cb21-4640-9552-ab745c5e979d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn-wrapper > fw-button[type=&quot;submit&quot;] > button.fw-button.fw-button-primary.only-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29fe51f8-0f33-4b82-968b-cac6cb012efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-button fw-button-primary only-icon</value>
      <webElementGuid>f27e383d-05f5-4330-b050-1377f5ca837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>fw-button</value>
      <webElementGuid>acc794f1-df89-42bf-801c-6546747d3056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>fw-button-primary,,only-icon</value>
      <webElementGuid>66c8bc34-6200-4d82-acc4-574ebc4410fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76ff9b90-ac16-40de-a5fd-c4a27e18350b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>817b6d26-cabf-469a-a0e3-c4e6f1ec87aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-tns-0-0 modal-open&quot;]/div[@class=&quot;modal modal-medium task-edit-modal ng-scope ng-isolate-scope modal-top in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-wrapper ng-scope&quot;]/table[1]/tbody[1]/tr[@class=&quot;modal-body&quot;]/td[@class=&quot;entity-holder&quot;]/div[@class=&quot;mask-holder&quot;]/div[@class=&quot;related-tasks section&quot;]/div[@class=&quot;related-column&quot;]/related-list[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;related-list&quot;]/form[@class=&quot;add-related-task-form form-inline ng-invalid ng-invalid-required ng-valid ng-dirty ng-valid-parse&quot;]/div[@class=&quot;btn-wrapper&quot;]/fw-button[1]/button[@class=&quot;fw-button fw-button-primary only-icon&quot;]</value>
      <webElementGuid>bd4d34a7-8f84-47f8-8b18-4e3be00c3778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>f69af8d0-5995-4e55-8227-5fcd5d5c547f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop files here to attach to this task'])[1]/following::button[1]</value>
      <webElementGuid>a7ecd7cb-a43d-4824-92cc-e9973364bb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop your files anywhere'])[1]/following::button[1]</value>
      <webElementGuid>075b78c0-af52-4640-ac26-76d68449af2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ New task'])[1]/preceding::button[2]</value>
      <webElementGuid>fb49b26f-93a1-4655-9564-a95d37c12da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::button[2]</value>
      <webElementGuid>0b9e9023-39ab-4814-a668-eb37714fbd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fw-button/button</value>
      <webElementGuid>3d48b167-cd59-40da-a617-6cc4b9806570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>01714bf1-0c78-4acf-a778-06900db704d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
