<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_taskTitle</name>
   <tag></tag>
   <elementGuidId>974da5b2-aaa3-4417-b4f7-08e998ae0c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-invalid.ng-invalid-required.inline.ng-untouched.ng-valid.input-sm.ng-not-empty.ng-dirty.ng-valid-parse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7395c77-1984-4e00-a17d-80a8f048c0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!area</value>
      <webElementGuid>be3ea5fd-1049-4fa8-81ad-9a3d55b4ed6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-invalid ng-invalid-required inline ng-untouched ng-valid input-sm ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>940ed60a-6f9e-4ed1-af20-f001d6c8f4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>2baff898-969e-4f11-baec-cd35e4fec93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0479c09-d5e9-438d-86f4-406629713cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-placeholder</name>
      <type>Main</type>
      <value>{{ placeholder }}</value>
      <webElementGuid>d040e816-aef8-4ea0-9b69-bd39053e28c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>focus()</value>
      <webElementGuid>1be946dd-3c39-4d70-9aec-3c2127426b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter title</value>
      <webElementGuid>daa840f6-6cbe-46ab-9822-178cef7cce9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-tns-0-0 modal-open&quot;]/div[@class=&quot;modal modal-medium task-edit-modal ng-scope ng-isolate-scope modal-top in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-wrapper ng-scope&quot;]/table[1]/tbody[1]/tr[@class=&quot;modal-body&quot;]/td[@class=&quot;entity-holder&quot;]/div[@class=&quot;mask-holder&quot;]/div[@class=&quot;related-tasks section&quot;]/div[@class=&quot;related-column&quot;]/related-list[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;related-list&quot;]/form[@class=&quot;add-related-task-form form-inline ng-invalid ng-invalid-required ng-valid ng-dirty ng-valid-parse&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;textcomplete-wrapper&quot;]/input[@class=&quot;form-control ng-invalid ng-invalid-required inline ng-untouched ng-valid input-sm ng-not-empty ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>d49c06e4-ba35-469b-9a23-5a5e4e41c519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='input']</value>
      <webElementGuid>b32a46cd-493e-4e8c-abbd-d6901e078591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>bf10acaa-a089-4468-b750-311a7c44ec41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'input' and @placeholder = 'Enter title']</value>
      <webElementGuid>4fa5885e-1e52-493d-91fb-dd3d01cbe04a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
