<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_hewTask</name>
   <tag></tag>
   <elementGuidId>a25f5268-d247-4e39-9f6a-1a54d5198b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.fw-button.fw-button-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f278ee76-a1a8-489f-9382-94292c4e0b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-button fw-button-primary</value>
      <webElementGuid>d6dfcf95-dccc-4245-ab1e-8c621705cfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>fw-button</value>
      <webElementGuid>8c193c20-6e2f-46a5-a158-8070c32a70cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>fw-button-primary,,</value>
      <webElementGuid>a6373e87-d361-45b0-a48a-a942a4be9a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85768a85-0568-4758-8f1b-f06a4e4d42aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea8e206f-bef8-440c-9e06-52053670ad40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New task</value>
      <webElementGuid>50989214-6c07-4bf7-bdab-f1d6515bf34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content-wrapper&quot;)/div[@class=&quot;inset page-content&quot;]/div[@class=&quot;innerLR&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;task-view-container ng-scope&quot;]/div[@class=&quot;fw-header-container&quot;]/div[@class=&quot;fw-header-row&quot;]/div[@class=&quot;fw-header-left&quot;]/fw-button[@class=&quot;ng-scope&quot;]/button[@class=&quot;fw-button fw-button-primary&quot;]</value>
      <webElementGuid>4796a79c-7db5-4009-885e-ccf8a75a04d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>6a5e7c04-5a1b-4f98-a352-c7b59a4de773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content-wrapper']/div/div/div[2]/div/div/div[3]/div/div/fw-button/button</value>
      <webElementGuid>0d8aad6b-2ef1-4d37-b729-cee5af152246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add tasks to organize and prioritize your project'])[1]/following::button[1]</value>
      <webElementGuid>ba0c2ea6-5948-4650-ad5c-34921b487c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import tasks'])[1]/preceding::button[1]</value>
      <webElementGuid>321fd2bb-7d01-430c-add9-b9425d1a2fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-button/button</value>
      <webElementGuid>57d2809a-2ce5-4c5b-91e8-274accf12a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'New task' or . = 'New task')]</value>
      <webElementGuid>cc049bea-0eee-4ed7-a482-aaacaa7bf80f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
