<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_toNavProjects</name>
   <tag></tag>
   <elementGuidId>490ba53f-d2e4-40df-a033-f0ec0c9a159b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ng-scope.selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='FIELDWIRE'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1cebdca-ebc6-4d22-864b-f6f5b9a6c5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>PROJECTS</value>
      <webElementGuid>53e65ab3-df25-4235-8f52-b2ae11a084f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.onTabClick('root.index.projects')</value>
      <webElementGuid>4fa60e48-d4cf-4507-97df-4f130decb8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ selected: $ctrl.currentRoute === 'root.index.projects' }</value>
      <webElementGuid>78fe973f-1707-4a9a-8b92-b89eb6459c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope selected</value>
      <webElementGuid>e2cddd8c-a410-4587-b20f-b110a738ea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Projects</value>
      <webElementGuid>af7fad0f-36ea-442b-b222-854c31bc2423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-tns-0-0 disable-window-scroll&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/nav-bar[@class=&quot;ng-scope ng-isolate-scope&quot;]/nav[@class=&quot;navbar navbar-custom navbar-fixed-top&quot;]/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;nav-tabs-wrapper hidden-xs ng-scope ng-isolate-scope&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/button[@class=&quot;ng-scope selected&quot;]</value>
      <webElementGuid>1743e342-af79-47c8-a402-5c9a490ba573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FIELDWIRE'])[1]/following::button[1]</value>
      <webElementGuid>a12a07ae-69bc-4318-becb-fa87282ad35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People'])[1]/preceding::button[1]</value>
      <webElementGuid>303100bc-6274-4a4c-841d-c7e7740a6394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/preceding::button[2]</value>
      <webElementGuid>0314f7d9-da8a-4a53-8bbb-1f8254b2c28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Projects']/parent::*</value>
      <webElementGuid>6d0f3a71-875d-4708-a477-1bc6cb2338be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f4dfb57a-e2b3-4313-8686-c0919c057b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Projects' or . = 'Projects')]</value>
      <webElementGuid>85905bfa-a0f9-42e6-bde7-953ba4f87e6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
