<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_closeButton</name>
   <tag></tag>
   <elementGuidId>cd26174a-4990-4182-9d11-158793e99a1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.close-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='New Project'])[1]/preceding::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d5a758a-c943-4f81-bd76-4cd98cf34ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-modal</value>
      <webElementGuid>be65e805-2974-477c-b292-50ee619d9fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$dismiss()</value>
      <webElementGuid>13dc1d7d-1d88-4f29-ade5-f12787e0082b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>1117779c-70ac-49ba-b546-015c711732de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-tns-0-0 disable-window-scroll modal-open&quot;]/div[@class=&quot;modal new-project-modal fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-wrapper ng-scope&quot;]/div[@class=&quot;modal-header&quot;]/div[@class=&quot;close-modal&quot;]</value>
      <webElementGuid>a7f73e9c-33c7-43b5-b8cd-c248162f8c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Project'])[1]/preceding::div[1]</value>
      <webElementGuid>1e03de3c-f999-4cf9-9607-9faea888c454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clone existing project'])[1]/preceding::div[4]</value>
      <webElementGuid>4532cfd5-b960-48fa-9fb1-f998bdfebfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>edf8d9ac-8acc-4cb0-8268-3e85b090d4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>d4dd51b5-9772-4b36-baa6-dbb53fa56688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×' or . = '×')]</value>
      <webElementGuid>30f4ad74-53ae-4dba-9f9b-60db01834eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
