<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_newProjectLogo</name>
   <tag></tag>
   <elementGuidId>3a084d45-a253-429a-b14a-9a67b6223ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.new-project-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>de562501-ad84-466f-b87b-a5ca41c4b2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-project-image</value>
      <webElementGuid>c2ea4563-585d-4a88-9d51-e316c0f3e775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>NewProject.1ae4c2b62c0934fff779db49acdeff42.png</value>
      <webElementGuid>892b1d4f-55f0-4029-ba4c-088fd059bb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>NewProject.1ae4c2b62c0934fff779db49acdeff42.png</value>
      <webElementGuid>9a62302a-a4bb-4493-a4bd-d0e3dbd65744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-tns-0-0 disable-window-scroll modal-open&quot;]/div[@class=&quot;modal new-project-modal fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-wrapper ng-scope&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;center&quot;]/img[@class=&quot;new-project-image&quot;]</value>
      <webElementGuid>cbf2b487-8eb1-453d-b838-867a9a02bd88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>398b40b8-92ef-4979-a27f-df871c9123f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'NewProject.1ae4c2b62c0934fff779db49acdeff42.png']</value>
      <webElementGuid>38d8b184-bf89-4d96-997a-7e1ca1a25575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
