<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_sideNav_Tasks</name>
   <tag></tag>
   <elementGuidId>27f7eecb-55a6-4cb9-9688-341c7bc3e209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-wrapper']/div/ul/div/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5f2b8a6-9a75-46a5-84f0-eb3b97d14e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>root.projects.project.tasks({ projectId: fieldwireData.currentProject.id })</value>
      <webElementGuid>384250cf-ab61-4d21-9e23-514e797f878c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>onTabSelect('Tasks')</value>
      <webElementGuid>adcdfd0c-c516-4e31-a0f9-0ad6924e1d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#!/projects/d339f1bb-f7c2-4edb-82ce-b09862842fc1/tasks</value>
      <webElementGuid>0cc45aec-8de4-47a8-8d6e-18d118a7ddb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              
              Tasks
            </value>
      <webElementGuid>0cf3bd2b-f90d-4a63-9e3f-317d04f9ceca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-wrapper&quot;)/div[@class=&quot;sidebar-content&quot;]/ul[@class=&quot;sidebar-nav&quot;]/div[1]/li[3]/a[1]</value>
      <webElementGuid>0ece3689-499a-48c2-a7c3-0c991e571ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-wrapper']/div/ul/div/li[3]/a</value>
      <webElementGuid>85ce2f77-7878-4dd5-98fd-ae3b0c4eb096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specifications'])[1]/following::a[1]</value>
      <webElementGuid>265aa213-cff5-4668-93be-6d6822c3717d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plans'])[1]/following::a[2]</value>
      <webElementGuid>adea86bb-94f5-4018-856c-d2a795c6f019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photos'])[1]/preceding::a[1]</value>
      <webElementGuid>167db504-be11-490b-b06a-a54ae5c4e146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#!/projects/d339f1bb-f7c2-4edb-82ce-b09862842fc1/tasks')]</value>
      <webElementGuid>0c449f06-40b6-4527-89f3-505a8bec4129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[3]/a</value>
      <webElementGuid>5a1564f0-1100-43df-8ee4-e3108b0b73de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#!/projects/d339f1bb-f7c2-4edb-82ce-b09862842fc1/tasks' and (text() = '
              
              Tasks
            ' or . = '
              
              Tasks
            ')]</value>
      <webElementGuid>5cc23f10-b6e5-4afa-a89d-764fa3c29081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
