<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_companyNameCheck</name>
   <tag></tag>
   <elementGuidId>943bf3b9-ad56-4902-899b-8910b69b5923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login']/form/fieldset/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fa.fa-check.fa-long-field.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50a9b23d-b7f6-46f3-9f93-ca366ca0f2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check fa-long-field ng-scope</value>
      <webElementGuid>7e188132-b7bf-4755-9b1b-14d3b3a228f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>inputStates.companyName.check</value>
      <webElementGuid>04c211d5-94aa-4e83-9d84-a63817877050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/form[@class=&quot;form-signin profile ng-dirty ng-valid-parse ng-invalid ng-invalid-required ng-valid-minlength ng-valid-pattern&quot;]/fieldset[1]/div[@class=&quot;fa fa-check fa-long-field ng-scope&quot;]</value>
      <webElementGuid>770d7318-15bd-4945-bcf9-95fa85b53388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/fieldset/div[2]</value>
      <webElementGuid>48a39637-129f-4712-a6dd-6bdd32238280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]</value>
      <webElementGuid>151b127d-3091-4dd9-9cf8-a6c722288018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
