<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_fieldwireLogo</name>
   <tag></tag>
   <elementGuidId>9e616f94-4d54-400b-a9bf-2abbe7708d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.login-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a6d006bd-5d88-47d3-a599-f2e7fa492ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-logo</value>
      <webElementGuid>3fa7d956-d5f9-4c20-a02c-42a91bbbeafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg</value>
      <webElementGuid>4fba07ae-805f-4aa0-ad93-19cd39d6b7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg</value>
      <webElementGuid>16e1167b-b9f7-4c3a-b079-900bc62d674f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/img[@class=&quot;login-logo&quot;]</value>
      <webElementGuid>56d3c662-6862-4915-9fd9-6713804a0a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/img</value>
      <webElementGuid>bf397df6-42e0-47be-87c2-1571ecf60b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>14e8b1df-4a19-4b1b-8c4e-aa13cd25c8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'Fieldwire-Hilti-logo.b6ca91f83eee22801b1d17ad920f98b6.svg']</value>
      <webElementGuid>f3758f81-1913-43e8-bc04-e66f92cb7ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
