<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_companyType</name>
   <tag></tag>
   <elementGuidId>55e71172-606a-41b1-bcaf-b925d5d6a951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='companyType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#companyType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f74e6488-144c-4dab-9edd-2806f2b765ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>company-size-dropdown form-control ng-untouched ng-empty ng-dirty ng-valid-parse ng-invalid ng-invalid-required</value>
      <webElementGuid>f4909585-32b4-4ef1-b1f4-4cc589640316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyType</value>
      <webElementGuid>8585696a-5579-4f93-b9a2-6122dc173c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>companyType</value>
      <webElementGuid>07da0cf6-5b04-4f3a-b6de-08295fce92a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>showCompanyAttributeFeedbackIcon('companyType')</value>
      <webElementGuid>e0106ff3-c609-44f1-b029-4efc92a60022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>changeDropdownColor('companyType')</value>
      <webElementGuid>0934ba3e-3901-4693-ba4f-ff63f8a23c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{ color: inputStates.companyType.textColor }</value>
      <webElementGuid>11072da2-fe2b-4f2d-b4b8-cad11c61cb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>input-validation</name>
      <type>Main</type>
      <value>companyAttributeCustomValidityFeedback('companyType')</value>
      <webElementGuid>66056e17-78ba-4eb7-a748-bed2bbde4b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee9dcbcc-c4db-49a0-88c1-9ae76072901f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>033fa2b4-f2bb-42a6-a245-5768d76bbb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Company type
          Specialty ContractorGeneral ContractorArchitect / EngineerOwner / DeveloperOther
        </value>
      <webElementGuid>44d129cc-9e8e-49e9-9f87-aea4caa609d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyType&quot;)</value>
      <webElementGuid>adca4361-a266-4e74-ae26-069ef385a251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='companyType']</value>
      <webElementGuid>b18662f9-ad9e-48b5-ad23-2a51fb79caac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/fieldset[2]/div/select</value>
      <webElementGuid>6e02f296-16b1-448c-966c-7ccafbb86b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete'])[1]/preceding::select[2]</value>
      <webElementGuid>294b471c-3994-4bff-b8c4-0f35e1ccdd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboard Shortcuts:'])[1]/preceding::select[2]</value>
      <webElementGuid>8329fa43-0f74-4c09-966d-6e94078323b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a6bca75f-17dc-44f5-b6d6-6c40b5c3de0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'companyType' and (text() = '
          Company type
          Specialty ContractorGeneral ContractorArchitect / EngineerOwner / DeveloperOther
        ' or . = '
          Company type
          Specialty ContractorGeneral ContractorArchitect / EngineerOwner / DeveloperOther
        ')]</value>
      <webElementGuid>af4bb297-379d-4aa7-b9a3-bb2e573adac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
